{{- if not (and .Values.global (and .Values.global.postgresql .Values.global.postgresql.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ if and .Values.global (and .Values.global.postgresql .Values.global.postgresql.secretName) }}{{ .Values.global.postgresql.secretName }}{{ else }}{{ .Release.Name }}-secret{{ end }}
  labels:
    app.kubernetes.io/name: citus-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: citus-cluster
type: Opaque
data:
  {{ default "postgres-password" (and .Values.global (and .Values.global.postgresql (and .Values.global.postgresql.secretKeys .Values.global.postgresql.secretKeys.passwordKey))) }}: {{ default "ChangeMeSecurePassword123!" (and .Values.global (and .Values.global.postgresql .Values.global.postgresql.password)) | b64enc | quote }}
{{- end }}
