{{- if and .Values.global (and .Values.global.serviceAccount .Values.global.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "citus-sa" .Values.global.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: citus-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: citus-cluster
{{- end }}
