apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-citus-worker-hl
  labels:
    app.kubernetes.io/name: citus-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    citus.role: worker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: {{ default 5432 (and .Values.global (and .Values.global.postgresql .Values.global.postgresql.port)) }}
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: citus-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    citus.role: worker
