{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-citus-coordinator" .Release.Name) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: citus-coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    citus.role: coordinator
{{- end }}
